#!/bin/bash


# Echo "Select cluster:"
# read cluster_name

# Echo "Enter butane file from $cluster_name:"

# select x in $(ls $cluster_name/fcos/ | grep '.bu' | grep -v '.ign')
# do
#     echo "Generating ignition file from $cluster_name/fcos/$x"
#     ignition_file=$cluster_name/fcos/$x | tr '.bu' '.ign'
#     echo $ignition_file
#     podman run --interactive --rm quay.io/coreos/butane:release --pretty --strict < $cluster_name/fcos/$x > $cluster_name/fcos/$x.ign
#     echo "Done"
#     exit 0
# done



# exit 0

# podman run --interactive --rm quay.io/coreos/butane:release --pretty --strict < node1.demo.bu > node1.demo.ign


echo "Enter /path/to/<file>.ign:"
read IGN_CONFIG

echo "Enter FCOS VM Name:"
read VM_NAME


# IGN_CONFIG=/opt/fcos-ops/fcos-nogpg.ign
IMAGE=/opt/fcos/images/fedora-coreos-36.20221014.3.1-qemu.x86_64.qcow2
# VM_NAME=node$1
VCPUS=2
RAM_MB=4096
DISK_GB=10
STREAM=stable

chcon --verbose --type svirt_home_t ${IGN_CONFIG}
virt-install --connect="qemu:///system" --name="${VM_NAME}" \
    --vcpus="${VCPUS}" --memory="${RAM_MB}" \
    --os-variant="fedora-coreos-$STREAM" --import --graphics=none \
    --disk="size=${DISK_GB},backing_store=${IMAGE}" \
    --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${IGN_CONFIG}"
