# https://kubevirt.io/user-guide/virtual_machines/virtual_machine_instances/
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: cirros-vm01.white-widow
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: kubevirt/cirros-container-disk-demo:latest
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitConfigDrive:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILUcbIaaK/Gq+UDa551OHGWZdFhuSmog4AEV3qFLLBsm core@node1.white-widow
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOpbPHVNgXkqWCrrxm/5hg8OmxOnPUiVXILdqn3M46Dj white-widow@t470.brq
